dist: trusty
sudo: false
language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pytz
- pip install restructuredtext-lint pygments
- pip install pydiatra pyflakes
script:
- ./aerozol --debug-badssl
- python3 -m pydiatra aerozol
- python3 -m pyflakes aerozol
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
