dist: xenial
language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8-dev"
install:
- python3 -m pip install pytz
- python3 -m pip install restructuredtext-lint pygments
- python3 -m pip install pydiatra pyflakes
script:
- ./aerozol --debug-badssl
- python3 -m pydiatra aerozol
- python3 -m pyflakes aerozol
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
