name: CI
permissions: {}
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: install deps
      run:
        python3 -m pip install cryptography
    - name: run TLS test
      run:
        ./aerozol --debug-badssl
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra --verbose aerozol
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes aerozol
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint --verbose aerozol
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
